<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<section class="completed">
	<h2 class="splash-head" style="margin-bottom: 1.5em;">Conclusions</h2>
	<dl class="splash-subhead" style="font-size: 120%;">
	<?php foreach ($domain->goals as $goal): ?>
		<?php if ($goal->hasAnswers() && (($answer = $goal->answer($state)) || $state->facts[$goal->name] != STATE_UNDEFINED)): ?>
			<dt><?=$state->substitute_variables($goal->description, ['Template', 'html'])?></dt>
			<div><?php
				echo $answer
					? $state->substitute_variables($answer->description, ['Template', 'html'])
					: '<pre>' . $state->facts[$goal->name] . '</pre>';
				?></div>
			<?php endif ?>
	<?php endforeach ?>
	</dl>
</section>
<?php $this->end() ?>