<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A user interface designed to express the Knowledge of an expert in an intuitive way.">    <title> X Knowledge Base</title>    
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/pure-min.css" integrity="sha384-" crossorigin="anonymous">
    
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-responsive-min.css">
    <!--<![endif]-->
    
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    
        <!--[if lte IE 8]>
            <link rel="stylesheet" href="css/layouts/marketing-old-ie.css">
        <![endif]-->
        <!--[if gt IE 8]><!-->
            <link rel="stylesheet" href="templates/css/layouts/marketing.css">
        <!--<![endif]-->

</head>

<body>

<?php if ($errors): ?>
		<section class="status-update">
			<p>The following errors occurred:</p>
			<ul>
				<?php foreach ($errors as $error): ?>
				<li title="<?=$this->attr(sprintf('%s:%d', $error->file, $error->line))?>"><?=$this->html($error->message)?></li>
				<?php endforeach ?>
			</ul>
		</section>
		<?php endif ?>

<!-- The main Knowledge Base System. -->

<div class="splash-container" id="first-page">
    <div class="splash">
        <h1 class="splash-head">Bob the Mechanic</h1>
        <p class="splash-subhead">
            Hi there! I am Bob and I fix cars. In this questioning session, I will try to identify what is wrong with your car and provide appropriate feedback on how to repair it.
        </p>
        <p>
            <a href="webfrontend.php?kb=car.xml" class="pure-button pure-button-primary">Get Started</a>
        </p>
    </div>
</div>

</body>
</html>